name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python requirements
        run: |
          pip install -r requirements.txt

      - name: Do all
        run: |
          ./build.sh

      - name: Save site
        uses: actions/upload-artifact@v3
        with:
          name: ant-design-site.zip
          path: |
            ant_design_site*.zip
